OrdererOrgs:
- Name: Orderer
  Domain: example.com
  EnableNodeOUs: true
  Specs:
   - Hostname: orderer
#--------------------------------------
PeerOrgs:
- Name: Org1
  Domain: org1.example.com
  EnableNodeOUs: true
#--------------
# Number of nodes/peers
  Template:
   Count: 2
   SANS:
    - "localhost"
# Number of non-admin users
  Users:
   Count: 1
#-------------------------------------
- Name: Org2
  Domain: org2.example.com
  EnableNodeOUs: true
#--------------
# Number of nodes/peers
  Template:
   Count: 1
   SANS:
    - "localhost"
# Number of non-admin users
  Users:
   Count: 1
